FROM spark:latest

# spark config
USER spark
WORKDIR /usr/local/spark/conf
COPY ./spark.conf/* ./
RUN sudo chown spark:spark ./* && \
    sudo chmod +x ./* && \
    sudo dos2unix *.sh

# spark make ssh
WORKDIR /home/spark/.ssh
RUN ssh-keygen -t rsa -N "" -f /home/spark/.ssh/id_rsa -C "spark@master" && \
    cat id_rsa.pub >> authorized_keys && \
    chmod 640 authorized_keys && \
    touch known_hosts

# all env config setting
USER root
WORKDIR /
COPY ./etc.profile.d/env.sh /etc/profile.d/
RUN chown root:root /etc/profile.d/env.sh && \
    dos2unix /etc/profile.d/env.sh